// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZFkjoGG3YAiIucwhPnMD31sTFKXBrgI',
    appId: '1:335040073706:web:8980901e282137445dec93',
    messagingSenderId: '335040073706',
    projectId: 'blog-app-db767',
    authDomain: 'blog-app-db767.firebaseapp.com',
    storageBucket: 'blog-app-db767.appspot.com',
    measurementId: 'G-KZZYBV2WXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdzySFYnXuryO6qv-b8lkHu4vGbdumZ0',
    appId: '1:335040073706:android:2453a10389e978145dec93',
    messagingSenderId: '335040073706',
    projectId: 'blog-app-db767',
    storageBucket: 'blog-app-db767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApE5BjEdZ1QgWDfq2UJuFLafKEYkWQ1ng',
    appId: '1:335040073706:ios:7b47744110ae310e5dec93',
    messagingSenderId: '335040073706',
    projectId: 'blog-app-db767',
    storageBucket: 'blog-app-db767.appspot.com',
    iosClientId: '335040073706-18237o134g360105ec23bdvudte6jigv.apps.googleusercontent.com',
    iosBundleId: 'com.exampl',
  );
}
